// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HMO.Models;

public partial class CoronaVaccine
{
    public int VaccineId { get; set; }

    public int? MemberId { get; set; }

    public DateOnly? DateVaccine { get; set; }

    public string ManufacturerVaccine { get; set; }

    public virtual Member Member { get; set; }
}