// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HMO.Models;

public partial class CoronaVirus
{
    public int VirusId { get; set; }

    public int? MemberId { get; set; }

    public DateOnly? DatePositiveResult { get; set; }

    public DateOnly? DateRecovery { get; set; }

    public virtual Member Member { get; set; }
}