// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HMO.Models;

public partial class HMOContext : DbContext
{
    public HMOContext(DbContextOptions<HMOContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CoronaVaccine> CoronaVaccines { get; set; }

    public virtual DbSet<CoronaVirus> CoronaViruses { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CoronaVaccine>(entity =>
        {
            entity.HasKey(e => e.VaccineId).HasName("PK__CoronaVa__45DC68894B59D0D4");

            entity.Property(e => e.VaccineId).ValueGeneratedNever();
            entity.Property(e => e.ManufacturerVaccine)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Member).WithMany(p => p.CoronaVaccines)
                .HasForeignKey(d => d.MemberId)
                .HasConstraintName("FK__CoronaVac__Membe__3D5E1FD2");
        });

        modelBuilder.Entity<CoronaVirus>(entity =>
        {
            entity.HasKey(e => e.VirusId).HasName("PK__CoronaVi__67A7A59BAF5B723C");

            entity.Property(e => e.VirusId).ValueGeneratedNever();

            entity.HasOne(d => d.Member).WithMany(p => p.CoronaViruses)
                .HasForeignKey(d => d.MemberId)
                .HasConstraintName("FK__CoronaVir__Membe__3A81B327");
        });

        modelBuilder.Entity<Member>(entity =>
        {
            entity.HasKey(e => e.MemberId).HasName("PK__Members__0CF04B18B19EAAB7");

            entity.HasIndex(e => e.IdentityCard, "UQ__Members__DA5B2F6DBB52BD81").IsUnique();

            entity.Property(e => e.MemberId).ValueGeneratedNever();
            entity.Property(e => e.ACity)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("A_City");
            entity.Property(e => e.ANumber)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("A_Number");
            entity.Property(e => e.AStreet)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("A_Street");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IdentityCard)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.MobilePhone)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Telephone)
                .HasMaxLength(15)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}