// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HMO.Models;

public partial class Member
{
    public int MemberId { get; set; }

    public string FullName { get; set; }

    public string IdentityCard { get; set; }

    public string ACity { get; set; }

    public string AStreet { get; set; }

    public string ANumber { get; set; }

    public DateOnly DateBirth { get; set; }

    public string Telephone { get; set; }

    public string MobilePhone { get; set; }

    public virtual ICollection<CoronaVaccine> CoronaVaccines { get; set; } = new List<CoronaVaccine>();

    public virtual ICollection<CoronaVirus> CoronaViruses { get; set; } = new List<CoronaVirus>();
}